import './js/data'
import './js/range-slider'
import './js/card-container'
import './js/filter-color'
import './js/filter-shape'
import './js/filter-size'
import './js/filter-favourite'
import './js/sort'
import './css/fonts.css'
import './css/style.css'
import './css/home-page.css'
import './css/toy-page.css'
import './css/range-slider.css'

